### ISSUE TITLE
Body Margins to be removed

### ISSUE THREAD

**Issue by yashsehgal** [DesignSystemsOSS/eccentrictouch#231]
**Describe the bug**
The centering body margins to be removed from CSS. 

```CSS
body {
    margin-right: auto;
    margin-left: auto;
    max-width: 1400px;
}
```

The code snippet given above has to be removed from the main `eccentric.scss` and `eccentric.css` modules.
