### ISSUE TITLE
[FEATURE] Prefixes for CSS custom properties, and class names.

### ISSUE THREAD

**Issue by MatteuSan** [DesignSystemsOSS/eccentrictouch#322]
### ⭐ Suggestion

Add prefixes to CSS custom properties, and class names for pre-made components/widgets
```css
/* Prefix = et */

:root {
    --et-custom-property: value;
}

.et-button {
    /* Button styles */
}
```
